### PR TITLE
Clarify jwksregistration obligtions

### PR DESCRIPTION
**Pull request by jmandel**
Clarify obligations based [on zulip discussion](https://chat.fhir.org/#narrow/stream/179170-smart/topic/is.20.60jwks_uri.60.20support.20required.20for.20SMART.20server.3F)

### CODE REVIEW

**Comment by isaacvetter** [comment]
This isn't a clarification, but rather adds new normative requirements that didn't previously exist. 

The stated justification is that some client developers may prefer to not host jwks urls. Is this a sufficient reason to require a server to support both methods?

Alternatively, if it's unreasonable for backend app to always host a jwks url, then shouldn't the spec require manually exchanged jwks and permit optional support for the url?

**Comment by jmandel** [comment]
This is a proposed clarification, reflecting our design intent and discussions. The aim is to invite comment, so thanks for the close look! Let's shift gears here: from your perspective @isaacvetter as a server developer, is there one of these approaches you'd rather not support, and if so: which and why?

(And to be clear, the underlying issue isn't about what clients prefer: it's about what's feasible for a given client architecture. Not all clients include an "online" server component; servers necessarily do.)

**Comment by jmandel** [comment]
From today's Argonaut Bulk Data call, @cooperthompson mentioned that ONC clarified expectations at FHIR Dev Days office hours last month -- that ONC expects servers to support both methods.

**Comment by jmandel** [comment]
@isaacvetter just checking back in -- given ONC's clarifications, do you have any outstanding concerns about aligning/clarifying our own spec as proposed here?

**Review by gotdan — APPROVED** [review]

**Pull request merged**
